# Generated by Django 5.0.1 on 2024-02-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('length', models.IntegerField(null=True)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('image', models.ImageField(default='default.jpg', null=True, upload_to='media/images/cover/')),
                ('url', models.URLField(null=True)),
                ('genre', models.ManyToManyField(to='films.genre')),
            ],
        ),
    ]
