# Generated by Django 5.0.1 on 2024-01-11 16:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_genre_film_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='length',
            field=models.IntegerField(null=True),
            preserve_default=False,
        ),
    ]
