# Generated by Django 5.0.1 on 2024-01-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_remove_film_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='length',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
