# Generated by Django 5.0.1 on 2024-01-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_film_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='genre',
            field=models.ManyToManyField(to='films.genre'),
        ),
        migrations.AlterField(
            model_name='film',
            name='length',
            field=models.IntegerField(null=True),
        ),
    ]
