# Generated by Django 5.0.1 on 2024-01-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0008_film_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
