# Generated by Django 5.0.1 on 2024-01-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0011_alter_film_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='image',
            field=models.ImageField(default='default.jpg', null=True, upload_to='media'),
        ),
    ]
