# Generated by Django 5.0.1 on 2024-01-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0014_alter_film_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='video',
            field=models.FileField(default='default.mp4', null=True, upload_to='media/films/'),
        ),
    ]
